---
- name: Establish install location.
  set_fact:
    omz_install_path: "{{ lookup('env', 'HOME') }}/{{ omz_install_directory }}"

- name: Clone Oh My ZSH repo for user.
  git:
    repo: "{{ omz_git_repository }}"
    dest: "{{ omz_install_path }}"
    update: true
    accept_hostkey: true
    version: "master"
  register: "omz_clone"

- name: Set ownership on newly cloned repository.
  file:
    path: "{{ omz_install_path }}"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    recurse: true
  when: "omz_clone is changed"

- name: "install plugin autosuggestions"
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: "install plugin zsh-syntax-highlighting"
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

- name: "install plugin zsh-syntax-highlighting"
  shell: git clone https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search

# Post setup
- name: "Set zsh as default shell"
  user: name={{ ansible_user_id }} shell=/bin/zsh
  become: true
  tags: omz
