---
- name: Bootstrap OSX dev machine
  hosts: all

  roles:

    - role: dotfiles
      tags: ["dotfiles"]

    - role: homebrew
      tags: ["homebrew"]

    - role: terminal
      tags: ["terminal"]
      